name: "Cargo set version"
description: "Updates package version of the cargo file"
inputs:
  cargoFile:
    description: "number of milliseconds to wait"
    required: true
    default: "Cargo.toml"
  version:
    description: "version string"
    required: true
outputs:
  content:
    description: "New cargo file content"
runs:
  using: "node16"
  main: "dist/index.js"
