name: "Cargo set version"
description: "Updates package version of the cargo file"
inputs:
  cargoFile:
    description: "cargo file location"
    required: true
    default: "Cargo.toml"
  buildNumberOnly:
    description: "if true, only update build number"
    required: false
    default: false
  overwriteCargoFile:
    description: "if true, overwrites target cargo file"
    required: false
    default: false
  version:
    description: "version string"
    required: true
outputs:
  content:
    description: "New cargo file content"
runs:
  using: "node16"
  main: "dist/index.js"
